// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKp-gIg4vX5CwoDJ1y_H1-khvdITF7KtM',
    appId: '1:889972692221:web:c4b190a12ea703d9eb1a94',
    messagingSenderId: '889972692221',
    projectId: 'flutter-chat-f086c',
    authDomain: 'flutter-chat-f086c.firebaseapp.com',
    storageBucket: 'flutter-chat-f086c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT07BwrTNZK1h5zo8FWMmLek9mClPUBcY',
    appId: '1:889972692221:android:f849e00a28a02840eb1a94',
    messagingSenderId: '889972692221',
    projectId: 'flutter-chat-f086c',
    storageBucket: 'flutter-chat-f086c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8iFS4BjtsSg7G5-FYDYEv5P_UMtZEW08',
    appId: '1:889972692221:ios:4054b3d70e95a7e7eb1a94',
    messagingSenderId: '889972692221',
    projectId: 'flutter-chat-f086c',
    storageBucket: 'flutter-chat-f086c.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8iFS4BjtsSg7G5-FYDYEv5P_UMtZEW08',
    appId: '1:889972692221:ios:4054b3d70e95a7e7eb1a94',
    messagingSenderId: '889972692221',
    projectId: 'flutter-chat-f086c',
    storageBucket: 'flutter-chat-f086c.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKp-gIg4vX5CwoDJ1y_H1-khvdITF7KtM',
    appId: '1:889972692221:web:10469fc7c6efc103eb1a94',
    messagingSenderId: '889972692221',
    projectId: 'flutter-chat-f086c',
    authDomain: 'flutter-chat-f086c.firebaseapp.com',
    storageBucket: 'flutter-chat-f086c.appspot.com',
  );
}
